version: "3"
services: # 服务列表
    nginx:
        image: nginx:latest #指定 nginx 镜像
        ports: # 将本机的 80 端口映射到容器的80端口
            - "80:80"
        container_name: feishiblog-nginx
        restart: always
        volumes: # 挂载卷
            - "/root/dockerconfig/nginx/nginx.conf:/etc/nginx/nginx.conf"
            - "/root/dockerconfig/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "/root/dockerconfig/nginx/www/dist:/usr/share/nginx/html"
        networks:
          - "my-network"
networks: # 网络
    my-network: # 网络名称
        driver: bridge

