version: "3"
services: # 服务列表
   nginx:
        image: nginx:latest #指定 nginx 镜像	
        ports: # 将本机的 80 端口映射到容器的80端口
            - "80:80"
        container_name: feishiblog-nginx
        restart: always
        volumes: # 挂载卷
            - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
            - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "./dist:/usr/share/nginx/html"

  
           