version: "3"
services: # 服务列表
   nginx:
        image: nginx:latest #指定 nginx 镜像	
        ports: # 将本机的 8080 端口映射到容器的80端口
            - "80:80"
        container_name: nginx-node
        restart: always
        volumes: # 挂载卷
            - "/Users/wangran/Desktop/wr/feishi-blog/nginx/nginx.conf:/etc/nginx/nginx.conf"
            - "/Users/wangran/Desktop/wr/feishi-blog/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "/Users/wangran/Desktop/wr/feishi-blog/dist:/usr/share/nginx/html"

  
           